$(()=>{
    $('#pag1-p1').on('click',()=>{
        localStorage.setItem('porcentaje',10)
    })
    $('#pag1-p2').on('click',()=>{
        localStorage.setItem('porcentaje',23)
    })
    $('#pag1-p3').on('click',()=>{
        localStorage.setItem('porcentaje',40)
    })
    $('#pag1-p4').on('click',()=>{
        localStorage.setItem('porcentaje',33)
    })
})